version: '3'

services:
  gymdb:
    container_name: gym-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gym
      MYSQL_ROOT_HOST: '%'
#      MYSQL_ALLOW_EMPTY_PASSWORD : true
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3308:3306"
#    volumes:
#      - ./db/data:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - gym_net

  gympring:
    container_name: gym-springboot
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gym-mysql:3306/gym?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - gymdb
    networks:
      - gym_net

networks:
  gym_net: